### ISSUE TITLE
0.5 test failures when building on Debian

### ISSUE THREAD

**Issue by sandrotosi** [matthew-brett/texext#1]
Hello,
im preparing texext for inclusion in Debian, and running tests while building the package, i got the following failures:

```
======================================================================
FAIL: texext.tests.test_docstrings.TestDocstrings.test_docstrings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/texext-0.5/.pybuild/cpython2_2.7_texext/build/texext/tests/test_docstrings.py", line 62, in test_docstrings
    assert_regexp_matches(html, self.expected_re)
AssertionError: Regexp didn't match: '<p>Here is the module docstring:</p>\\n<span class="target" id="module-texext.tests.for_docstrings"></span><p>A module to test docstring parsing with math such as <span class="math">\\\\\\(\\\\gamma = \\\\cos\\(\\\\alpha\\)\\\\\\)</span></p>\\n<p>Need to test other markup - so: <a class="reference external" href="https://github\\.com">a link</a>\\.</p>\\n<p>Here is the <(code|tt) class="docutils literal"><span class="pre">func</span></(code|tt)> docstring:</p>\\n<dl class="function">\\n<dt id="texext.tests.for_docstrings\\.func">\\n<(code|tt) class="descclassname">texext.tests.for_docstrings\\.</(code|tt)><(code|tt) class="descname">func</(code|tt)>(<span class="sig-paren">\\(</span><span class="sig-paren">\\)</span>|<big>\\(</big><big>\\)</big>)<a class="headerlink" href="#texext.tests.for_docstrings\\.func" title="Permalink to this definition">.+</a></dt>\\n<dd><p>A docstring with math in first line <span class="math">\\\\\\(z = \\\\beta\\\\\\)</span></p>\\n<p>With some more <span class="math">\\\\\\(a = 1\\\\\\)</span> math\\. Math across lines - <span class="math">\\\\\\(b\\n= 2\\\\\\)</span>\\.</p>\\n<p>Further, there is a <a class="reference external" href="https://python\\.org">link</a> and a substituted\\.</p>\\n</dd></dl>' not found in u'\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n\n<html xmlns="http://www.w3.org/1999/xhtml">\n  <head>\n    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n    <title>&lt;no title&gt; &#8212; Python  documentation</title>\n    <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />\n    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />\n    <script type="text/javascript" src="_static/documentation_options.js"></script>\n    <script type="text/javascript" src="_static/jquery.js"></script>\n    <script type="text/javascript" src="_static/underscore.js"></script>\n    <script type="text/javascript" src="_static/doctools.js"></script>\n    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>\n    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>\n    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>\n    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>\n    <link rel="index" title="Index" href="genindex.html" />\n    <link rel="search" title="Search" href="search.html" />\n    <link rel="prev" title="&lt;no title&gt;" href="contents.html" />\n   \n  <link rel="stylesheet" href="_static/custom.css" type="text/css" />\n  \n  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />\n\n  </head><body>\n  \n\n    <div class="document">\n      <div class="documentwrapper">\n        <div class="bodywrapper">\n          <div class="body" role="main">\n            \n  <p>Here is the module docstring:</p>\n<span class="target" id="module-texext.tests.for_docstrings"></span><p>A module to test docstring parsing with math such as <span class="math notranslate">\\(\\gamma = \\cos(\\alpha)\\)</span></p>\n<p>Need to test other markup - so: <a class="reference external" href="https://github.com">a link</a>.</p>\n<p>Here is the <code class="docutils literal notranslate"><span class="pre">func</span></code> docstring:</p>\n<dl class="function">\n<dt id="texext.tests.for_docstrings.func">\n<code class="descclassname">texext.tests.for_docstrings.</code><code class="descname">func</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#texext.tests.for_docstrings.func" title="Permalink to this definition">\xb6</a></dt>\n<dd><p>A docstring with math in first line <span class="math notranslate">\\(z = \\beta\\)</span></p>\n<p>With some more <span class="math notranslate">\\(a = 1\\)</span> math. Math across lines - <span class="math notranslate">\\(b\n= 2\\)</span>.</p>\n<p>Further, there is a <a class="reference external" href="https://python.org">link</a> and a substituted.</p>\n</dd></dl>\n\n\n\n          </div>\n        </div>\n      </div>\n      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">\n        <div class="sphinxsidebarwrapper"><div class="relations">\n<h3>Related Topics</h3>\n<ul>\n  <li><a href="contents.html">Documentation overview</a><ul>\n      <li>Previous: <a href="contents.html" title="previous chapter">&lt;no title&gt;</a></li>\n  </ul></li>\n</ul>\n</div>\n  <div role="note" aria-label="source link">\n    <h3>This Page</h3>\n    <ul class="this-page-menu">\n      <li><a href="_sources/a_page.rst.txt"\n            rel="nofollow">Show Source</a></li>\n    </ul>\n   </div>\n<div id="searchbox" style="display: none" role="search">\n  <h3>Quick search</h3>\n    <div class="searchformwrapper">\n    <form class="search" action="search.html" method="get">\n      <input type="text" name="q" />\n      <input type="submit" value="Go" />\n      <input type="hidden" name="check_keywords" value="yes" />\n      <input type="hidden" name="area" value="default" />\n    </form>\n    </div>\n</div>\n<script type="text/javascript">$(\'#searchbox\').show(0);</script>\n        </div>\n      </div>\n      <div class="clearer"></div>\n    </div>\n    <div class="footer">\n      &copy;.\n      \n      |\n      Powered by <a href="http://sphinx-doc.org/">Sphinx 1.7.2</a>\n      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.8</a>\n      \n      |\n      <a href="_sources/a_page.rst.txt"\n          rel="nofollow">Page source</a>\n    </div>\n\n    \n\n    \n  </body>\n</html>'

======================================================================
FAIL: texext.tests.test_tinypages.TestTinyPages.test_some_math
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/texext-0.5/.pybuild/cpython2_2.7_texext/build/texext/tests/test_tinypages.py", line 94, in test_some_math
    assert_true(tree_str in (expected_late, expected_early))
AssertionError: False is not true

======================================================================
FAIL: texext.tests.test_tinypages.TestTopLevel.test_some_math
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/texext-0.5/.pybuild/cpython2_2.7_texext/build/texext/tests/test_tinypages.py", line 94, in test_some_math
    assert_true(tree_str in (expected_late, expected_early))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 17 tests in 1.658s

FAILED (failures=3)
```

**Comment by matthew-brett** [comment]
Thanks for the report.  What version of Sphinx are you running against?  Is there any way for me to replicate your environment?

**Comment by sandrotosi** [comment]
sphinx version is 1.7.2, built in an isolated (chroot) up-to-date debian unstable environment. in debian development we usually use a tool called `pbuilder` to create such a chroot, but if you dont have a debian system where to run pbuilder probably the easiest option is a VM of some sort

**Comment by sandrotosi** [comment]
nope, we tent to prefer to base our packages to what's released on PyPI, but i see there are only to commits after 0.5 release (the second being a fixup for the  first) so i'll try to pull in both and see how that goes, thanks!

**Comment by sandrotosi** [comment]
thanks @matthew-brett  those are all gone away, but now there is:

```
I: pybuild base:217: cd /build/texext-0.6/.pybuild/cpython2_2.7_texext/build; python2.7 -m nose 
E
======================================================================
ERROR: test suite for <module 'texext' from '/build/texext-0.6/.pybuild/cpython2_2.7_texext/build/texext/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 469, in try_run
    return func(obj)
  File "/build/texext-0.6/.pybuild/cpython2_2.7_texext/build/texext/__init__.py", line 12, in setup
    math_dollar.setup(app)
  File "/build/texext-0.6/.pybuild/cpython2_2.7_texext/build/texext/math_dollar.py", line 205, in setup
    app.add_transform(MathDollarTransform)
AttributeError: 'module' object has no attribute 'add_transform'

----------------------------------------------------------------------
Ran 0 tests in 0.069s

FAILED (errors=1)
```

**Comment by matthew-brett** [comment]
It looks like you're trying to run the tests with nose - the new version uses pytest.

**Comment by sandrotosi** [comment]
you're right! running the via pytest works perfectly - thanks!

**Comment by matthew-brett** [comment]
Closing - please re-open if this is still a problem.
