### ISSUE TITLE
problem installing with pip

### ISSUE THREAD

**Issue by jonathan-taylor** [matthew-brett/texext#6]
See: L1426 of https://travis-ci.org/jonathan-taylor/regreg/jobs/658982438?utm_medium=notification&utm_source=github_status

Also:

(py36) ~/git-repos/regreg/regreg/paths (master) $ pip install -U texext
Collecting texext
  Downloading https://files.pythonhosted.org/packages/aa/bb/a08988546bb35d770b510be6a94b0f38068f698acd3e871358400ee99f86/texext-0.6.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/jonathantaylor/anaconda/envs/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r1/yzxk5h4j5r327ymmt5msy3n00000gr/T/pip-install-xs6galw5/texext/setup.py'"'"'; __file__='"'"'/private/var/folders/r1/yzxk5h4j5r327ymmt5msy3n00000gr/T/pip-install-xs6galw5/texext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r1/yzxk5h4j5r327ymmt5msy3n00000gr/T/pip-install-xs6galw5/texext/pip-egg-info
         cwd: /private/var/folders/r1/yzxk5h4j5r327ymmt5msy3n00000gr/T/pip-install-xs6galw5/texext/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r1/yzxk5h4j5r327ymmt5msy3n00000gr/T/pip-install-xs6galw5/texext/setup.py", line 10, in <module>
        with open('requirements.txt', 'rt') as fobj:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(py36) ~/git-repos/regreg/regreg/paths (master) $

**Comment by matthew-brett** [comment]
Yup - thanks - should be fixed now.

**Comment by jonathan-taylor** [comment]
Yup, thanks.
________________________________
